import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const adwaitaMono = localFont({
  src : "../public/AdwaitaMono-Regular.ttf",
  weight:"400",
  style:"normal",
  variable: "--font-adwaita-mono",
  
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${adwaitaMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
